### ISSUE TITLE
Corrupted template

### ISSUE THREAD

**Issue by jiririedl** [userexec/Sendy-BEE-free-Uploader#3]
I create a template in BeeFree and then I download it. [download](https://ufile.io/4361e)

I import my zip file (with the downloaded template) from BeeFree to sendy. After import I check a source code in sendy and I'll find mistakes in html declaration. 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Empty Template</title>
    <style></style>
</head>
<body>
  
</body>
</html>
<title></title>
<style>
</style>
...
template code
...
(<div></div>)
```

I found problem in closing tag of head and body (`</body>` and `</html>`) elements even before the code of a BeeFree template. The template alone in not inside body and html tag.

Some mail clients is ok with it and some not. For example SOGo show just empty email.
____________________

Main reason for this problems is probably sendy's default html declaration in source code. However when you delete this code and click for import BeeFree zip file and then you go check the source code you'll find out corrupted code again - sendy always fill empty source code with a html declaration, so you can't escape this problem easily. 
Only solution if manual correction of a source code imported from BeeFree - I move a closing tags (`</body>` and `</html>`) to the end and then I move` </head>` and `<body>` after closing tag of style element `</style>` and erase one of two `<title></title>` elements.

**Comment by userexec** [comment]
Issue fixed in [59f8f74](https://github.com/userexec/Sendy-BEE-free-Uploader/commit/59f8f7456aceb2b3d00a0a1bf2bb3e25de1c1291) by running regexes on the incoming BEEFree HTML to identify <head>, <body>, body class, and body styles content, then inserting those into CKEditor's existing mandatory HTML structure.

Previously this plugin was inserting all BEEFree HTML directly into CKEditor's HTML structure body, causing the extra structure then within CKEditor's body tag to be sanitized out.
